wandb_version: 1

batch_size:
  value: 512
conv1_kernel_size:
  value: 14
dilation_kernel_size:
  value: 5
dropout_rate:
  value: 0.036288435784529983
filters:
  value: 128
input_seq_len:
  value: 3000
learning_rate:
  value: 0.0005420184382197396
n_dil_layers:
  value: 10
out_pred_len:
  value: 2500
