wandb_version: 1

batch_size:
  value: 512
conv1_kernel_size:
  value: 13
dilation_kernel_size:
  value: 7
dropout_rate:
  value: 0.19758378907196616
filters:
  value: 32
input_seq_len:
  value: 3000
learning_rate:
  value: 0.0008369403130090539
n_dil_layers:
  value: 4
out_pred_len:
  value: 2250
