wandb_version: 1

batch_size:
  value: 128
conv1_kernel_size:
  value: 8
dilation_kernel_size:
  value: 4
dropout_rate:
  value: 0.19748485359301957
filters:
  value: 64
input_seq_len:
  value: 4000
learning_rate:
  value: 0.00045403740305695155
n_dil_layers:
  value: 9
out_pred_len:
  value: 1500
