wandb_version: 1

batch_size:
  value: 64
conv1_kernel_size:
  value: 7
dilation_kernel_size:
  value: 5
dropout_rate:
  value: 0.002537410606821866
filters:
  value: 16
input_seq_len:
  value: 2000
learning_rate:
  value: 0.0008667825862352046
n_dil_layers:
  value: 2
out_pred_len:
  value: 2000
