wandb_version: 1

batch_size:
  value: 128
conv1_kernel_size:
  value: 11
dilation_kernel_size:
  value: 7
dropout_rate:
  value: 0.16855090645331774
filters:
  value: 64
input_seq_len:
  value: 4000
learning_rate:
  value: 0.0007045979565123831
n_dil_layers:
  value: 6
out_pred_len:
  value: 2250
