wandb_version: 1

batch_size:
  value: 64
conv1_kernel_size:
  value: 10
dilation_kernel_size:
  value: 7
dropout_rate:
  value: 0.045325572508789685
filters:
  value: 32
input_seq_len:
  value: 5000
learning_rate:
  value: 0.00023695597875827005
n_dil_layers:
  value: 2
out_pred_len:
  value: 1500
