_wandb:
    value:
        cli_version: 0.18.3
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 9
                - 55
                - 103
            "2":
                - 1
                - 9
                - 55
                - 103
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.8.20
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
conv1_kernel_size:
    value: 21
dilation_kernel_size:
    value: 3
dropout_rate:
    value: 0
filters:
    value: 64
learning_rate:
    value: 0.001
n_dil_layers:
    value: 9
out_pred_len:
    value: 1000
sequence_len:
    value: 3107
