wandb_version: 1

batch_size:
  value: 16
conv1_kernel_size:
  value: 10
dilation_kernel_size:
  value: 11
dropout_rate:
  value: 0.026379012184571463
filters:
  value: 64
input_seq_len:
  value: 5000
learning_rate:
  value: 0.005723971801486371
n_dil_layers:
  value: 4
out_pred_len:
  value: 2000
