_wandb:
    value:
        cli_version: 0.18.3
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 9
                - 55
                - 103
            "2":
                - 1
                - 9
                - 55
                - 103
            "3":
                - 7
                - 16
                - 23
                - 55
                - 66
            "4": 3.8.20
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
batch_size:
    value: 24
conv1_kernel_size:
    value: 23
cts_bw_file:
    value: /gladstone/corces/lab/users/vishvak/chrombpnet_tutorial/own_data/ENCFF735AHG.bigWig
dilation_kernel_size:
    value: 7
dropout_rate:
    value: 0.2
filters:
    value: 96
genome_fasta:
    value: /gladstone/corces/lab/users/vishvak/chrombpnet_tutorial/data/downloads/hg38.fa
input_seq_len:
    value: 3107
learning_rate:
    value: 0.001894
n_dil_layers:
    value: 8
negative_sampling_ratio:
    value: 0
nonpeak_regions:
    value: /gladstone/corces/lab/users/vishvak/chrombpnet_tutorial/own_data/test.chr1.negatives.adjusted.bed
out_pred_len:
    value: 1500
peak_regions:
    value: /gladstone/corces/lab/users/vishvak/chrombpnet_tutorial/own_data/test.chr1_to_chr10.no_blacklist.bed
seq_focus_len:
    value: 1000
sequence_len:
    value: 3107
train_chrs:
    value:
        - chr1
        - chr2
        - chr3
        - chr4
        - chr5
train_size:
    value: 0.6
valid_chrs:
    value:
        - chr6
        - chr7
