wandb_version: 1

batch_size:
  value: 64
conv1_kernel_size:
  value: 12
dilation_kernel_size:
  value: 4
dropout_rate:
  value: 0.07472527667081699
filters:
  value: 16
input_seq_len:
  value: 6000
learning_rate:
  value: 0.00010411128547620976
n_dil_layers:
  value: 8
out_pred_len:
  value: 2250
