wandb_version: 1

batch_size:
  value: 512
conv1_kernel_size:
  value: 12
dilation_kernel_size:
  value: 9
dropout_rate:
  value: 0.03907491770180709
filters:
  value: 256
input_seq_len:
  value: 6000
learning_rate:
  value: 0.006189774272696644
n_dil_layers:
  value: 3
out_pred_len:
  value: 1500
