wandb_version: 1

batch_size:
  value: 256
conv1_kernel_size:
  value: 12
dilation_kernel_size:
  value: 7
dropout_rate:
  value: 0.09971489226308172
filters:
  value: 128
input_seq_len:
  value: 3000
learning_rate:
  value: 0.0010405270178252325
n_dil_layers:
  value: 6
out_pred_len:
  value: 2000
