wandb_version: 1

batch_size:
  value: 256
conv1_kernel_size:
  value: 10
dilation_kernel_size:
  value: 3
dropout_rate:
  value: 0.14125597358167766
filters:
  value: 32
input_seq_len:
  value: 2000
learning_rate:
  value: 0.008936800798087993
n_dil_layers:
  value: 6
out_pred_len:
  value: 1500
